# Generated by Django 3.2.6 on 2021-09-21 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0003_rename_dateofjoining_supplier_dateofjoining'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('unitOfMeasurement', models.CharField(choices=[('KG', 'Kilograma'), ('G', 'Grama'), ('L', 'Litro'), ('ML', 'Mililitro')], max_length=2)),
                ('registrationDate', models.DateField()),
                ('purchasePrice', models.FloatField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('purchaseDate', models.DateField()),
                ('quantity', models.FloatField(max_length=6)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suppliers.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='individualPurchasePrice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('purchasePrice', models.FloatField(max_length=6)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suppliers.supplier')),
            ],
        ),
    ]
