# Generated by Django 3.2.6 on 2021-09-21 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individualpurchaseprice',
            old_name='purchasePrice',
            new_name='purchase_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='purchasePrice',
            new_name='purchase_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='registrationDate',
            new_name='registration_date',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='unitOfMeasurement',
            new_name='unit_measurement',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='purchaseDate',
            new_name='purchase_date',
        ),
    ]
