# Generated by Django 3.2.6 on 2021-10-11 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weeklycontrol', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='week',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='weeklycontrol.week'),
        ),
    ]
