# Generated by Django 3.2.6 on 2021-09-28 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210921_0014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='purchase_date',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='quantity',
        ),
        migrations.AddField(
            model_name='purchase',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchase',
            name='date_end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='date_start',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchase_closing_date',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='WeeklyCollection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True)),
                ('quantity', models.FloatField(max_length=6, null=True)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.purchase')),
            ],
        ),
    ]
