# Generated by Django 3.2.6 on 2021-10-02 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210927_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_start', models.DateField(null=True)),
                ('date_end', models.DateField(null=True)),
            ],
        ),
    ]
