# Generated by Django 3.2.6 on 2021-10-02 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='date_end',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='date_start',
        ),
    ]
