# Generated by Django 3.2.6 on 2021-10-02 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20211002_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='week',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='products.week'),
        ),
    ]
