# Generated by Django 3.2.6 on 2021-10-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weeklycontrol', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklycollection',
            name='date',
            field=models.DateField(),
        ),
    ]
