# Generated by Django 3.2.6 on 2021-09-12 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Suppliers',
            new_name='Supplier',
        ),
    ]
