# Generated by Django 3.2.6 on 2021-09-17 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_rename_suppliers_supplier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='DateOfJoining',
            new_name='dateOfJoining',
        ),
    ]
